[workspace]
resolver = "3"

members = [
    "elkengine_core",
    "elktracer_benchmarks",
    "elktracer_cli",
    "elktracer_core",
    "elktracer_editor",
]

[workspace.dependencies]
# Logging
log = "0.4.26"
