[package]
name = "elktracer_core"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-Z", "threads=8"]

[dependencies]
# Logging
env_logger = "0.11.6"
log = { workspace = true }

image = "0.25.5"
