[package]
name = "elktracer_core"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = false
path = "src/lib.rs"

[dependencies]
# Logging
env_logger = "0.11.6"
log = { workspace = true }

image = "0.25.5"
rand = "0.9.0"
