[package]
name = "elktracer_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
elktracer_core = { path = "../elktracer_core" }
elktracer_json = { path = "../elktracer_json" }
clap = { version = "4.5.37", features = ["derive"] }
# Logging
log = { workspace = true }
