[package]
name = "elktracer_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
elktracer_core = { path = "../elktracer_core" }
elkengine_core = { path = "../elkengine_core" }
# Logging
log = { workspace = true }
